# Generated by Django 2.2.4 on 2019-09-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='product')),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
