# Generated by Django 2.2.5 on 2019-09-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='likes',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
